general_common_woman_names = {
    'Jessica',
    'Ashley',
    'Amanda',
    'Sarah',
    'Jennifer',
    'Emily',
    'Samantha',
    'Elizabeth',
    'Stephanie',
    'Lauren',
    'Nicole',
    'Brittany',
    'Megan',
    'Rachel',
    'Hannah',
    'Kayla',
    'Melissa',
    'Amber',
    'Danielle',
    'Taylor',
    'Rebecca',
    'Heather',
    'Alexis',
    'Michelle',
    'Katherine',
    'Tiffany',
    'Kimberly',
    'Victoria',
    'Alyssa',
    'Christina',
    'Courtney',
    'Madison',
    'Laura',
    'Jasmine',
    'Sara',
    'Amy',
    'Mary',
    'Anna',
    'Erin',
    'Crystal',
    'Brianna',
    'Andrea',
    'Abigail',
    'Alexandra',
    'Olivia',
    'Allison',
    'Morgan',
    'Emma',
    'Kelly',
    'Maria',
    'Natalie',
    'Angela',
    'Erica',
    'Vanessa',
    'Chelsea',
    'Kristen',
    'Julia',
    'Kelsey',
    'Lindsey',
    'Katie',
    'Jamie',
    'Haley',
    'Kaitlyn',
    'Kathryn',
    'Shannon',
    'Brooke',
    'Alicia',
    'Grace',
    'Jacqueline',
    'Jenna',
    'Sydney',
    'Lisa',
    'Cassandra',
    'Jordan',
    'Shelby',
    'Lindsay',
    'Caitlin',
    'Destiny',
    'Katelyn',
    'Catherine',
    'Christine',
    'Marissa',
    'Monica',
    'Savannah',
    'Paige',
    'Gabrielle',
    'April',
    'Kristin',
    'Leah',
    'Diana',
    'Whitney',
    'Julie',
    'Brittney',
    'Sophia',
    'Caroline',
    'Erika',
    'Sierra',
    'Isabella',
    'Hailey',
    'Molly',
}

spanish_common_woman_names = {
    'Sofía',
    'Valentina',
    'Camila',
    'Isabella',
    'Mariana',
    'Valeria',
    'Sara',
    'Daniela',
    'Gabriela',
    'María José',
    'Victoria',
    'Martina',
    'Mía',
    'Lucía',
    'Ximena',
    'Catalina',
    'Luciana',
    'Natalia',
    'María Fernanda',
    'Fernanda',
    'Nicole',
    'Samantha',
    'Antonella',
    'Allison',
    'Abril',
    'Alejandra',
    'Emily',
    'Julieta',
    'Emma',
    'Ana Sofía',
    'Jazmín',
    'Paula',
    'Andrea',
    'Emilia',
    'Juliana',
    'Ashley',
    'Renata',
    'Juana',
    'Antonia',
    'Danna',
    'Melanie',
    'Guadalupe',
    'Valery',
    'Laura',
    'Luna',
    'María',
    'Abigail',
    'Zoe',
    'Génesis',
    'Agustina',
    'Manuela',
    'Ariana',
    'Regina',
    'Constanza',
    'Adriana',
    'Morena',
    'Josefina',
    'Florencia',
    'Brianna',
    'Carla',
    'Maite',
    'Alexa',
    'Carolina',
    'Alexandra',
    'María Camila',
    'Bianca',
    'Amanda',
    'Micaela',
    'Delfina',
    'Salomé',
    'Elena',
    'Ana',
    'Alma',
    'Miranda',
    'Bárbara',
    'Paola',
    'Fátima',
    'Monserrat',
    'Michelle',
    'Fabiana',
    'Sara Sofía',
    'Milagros',
    'Paulina',
    'Angelina',
    'Ivanna',
    'Isabel',
    'Rebeca',
    'María Paula',
    'Melissa',
    'Romina',
    'Candela',
    'Ana María',
    'Pilar',
    'Natalie',
    'Verónica',
    'Lola',
    'Mariángel',
    'Aitana',
    'Luana',
    'Isidora',
}

woman_names = general_common_woman_names.union(spanish_common_woman_names)

man_names = {
    'Michael',
    'Christopher',
    'Matthew',
    'Joshua',
    'Daniel',
    'David',
    'Andrew',
    'James',
    'Joseph',
    'John',
    'Nicholas',
    'Ryan',
    'Jacob',
    'Brandon',
    'Justin',
    'Robert',
    'William',
    'Anthony',
    'Jonathan',
    'Tyler',
    'Zachary',
    'Kevin',
    'Kyle',
    'Thomas',
    'Alexander',
    'Jason',
    'Brian',
    'Eric',
    'Benjamin',
    'Adam',
    'Steven',
    'Austin',
    'Aaron',
    'Timothy',
    'Samuel',
    'Nathan',
    'Jordan',
    'Jose',
    'Richard',
    'Cody',
    'Charles',
    'Christian',
    'Sean',
    'Jeremy',
    'Dylan',
    'Patrick',
    'Mark',
    'Jeffrey',
    'Stephen',
    'Ethan',
    'Travis',
    'Jesse',
    'Bryan',
    'Cameron',
    'Paul',
    'Juan',
    'Kenneth',
    'Dustin',
    'Scott',
    'Caleb',
    'Alex',
    'Gregory',
    'Jared',
    'Logan',
    'Gabriel',
    'Luis',
    'Noah',
    'Evan',
    'Derek',
    'Carlos',
    'Hunter',
    'Nathaniel',
    'Ian',
    'Bradley',
    'Edward',
    'Luke',
    'Trevor',
    'Marcus',
    'Shawn',
    'Corey',
    'Connor',
    'Antonio',
    'Devin',
    'Jesus',
    'Peter',
    'Isaac',
    'Seth',
    'Blake',
    'Jack',
    'Adrian',
    'Shane',
    'Angel',
    'Elijah',
    'Victor',
    'Taylor',
    'Isaiah',
    'Garrett',
    'Lucas',
    'George',
    'Miguel',
}

bay_area_city_names = {
    'Alameda',
    'Albany',
    'American Canyon',
    'Antioch',
    'Atherton',
    'Belmont',
    'Belvedere',
    'Benicia',
    'Berkeley',
    'Brentwood',
    'Brisbane',
    'Burlingame',
    'Calistoga',
    'Campbell',
    'Clayton',
    'Cloverdale',
    'Colma',
    'Concord',
    'Corte Madera',
    'Cotati',
    'Cupertino',
    'Daly City',
    'Danville',
    'Dixon',
    'Dublin',
    'East Palo Alto',
    'El Cerrito',
    'Emeryville',
    'Fairfax',
    'Fairfield',
    'Foster City',
    'Fremont',
    'Gilroy',
    'Half Moon Bay',
    'Hayward',
    'Healdsburg',
    'Hercules',
    'Hillsborough',
    'Lafayette',
    'Larkspur',
    'Livermore',
    'Los Altos',
    'Los Altos Hills',
    'Los Gatos',
    'Martinez',
    'Menlo Park',
    'Mill Valley',
    'Millbrae',
    'Milpitas',
    'Monte Sereno',
    'Moraga',
    'Morgan Hill',
    'Mountain View',
    'Napa',
    'Newark',
    'Novato',
    'Oakland',
    'Oakley',
    'Orinda',
    'Pacifica',
    'Palo Alto',
    'Petaluma',
    'Piedmont',
    'Pinole',
    'Pittsburg',
    'Pleasant Hill',
    'Pleasanton',
    'Portola Valley',
    'Redwood City',
    'Richmond',
    'Rio Vista',
    'Rohnert Park',
    'Ross',
    'San Anselmo',
    'San Bruno',
    'San Carlos',
    'San Francisco',
    'San Jose',
    'San Leandro',
    'San Mateo',
    'San Pablo',
    'San Rafael',
    'San Ramon',
    'Santa Clara',
    'Santa Rosa',
    'Saratoga',
    'Sausalito',
    'Sebastopol',
    'Sonoma',
    'South San Francisco',
    'St. Helena',
    'Suisun City',
    'Sunnyvale',
    'Tiburon',
    'Union City',
    'Vacaville',
    'Vallejo',
    'Walnut Creek',
    'Windsor',
    'Woodside',
    'Yountville',
}